import { useMemo, useState } from 'react';
import { PRESETS, instantiatePreset, launchDecision } from '../model/presets';
import { buildProject } from '../model/buildParts';
import { createDigitalBom } from '../model/bom';

type Summary = { days: number; events: number; visitors: number; sessions: number; funnel: {event:string;count:number}[]; daily:[string,number][]; products:[string,number][]; sources:[string,number][]; devices:[string,number][] };
const label = (s:string) => s.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase());
export default function AnalyticsDashboard() {
  const [token, setToken] = useState(() => sessionStorage.getItem('hon_analytics_token') || '');
  const [data, setData] = useState<Summary | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const products = useMemo(() => PRESETS.map((p) => { const bom = createDigitalBom(buildProject(instantiatePreset(p))); return { p, bom, launch: launchDecision(p) }; }).sort((a,b) => a.launch.priority-b.launch.priority), []);
  const load = async () => { setBusy(true); setError(''); sessionStorage.setItem('hon_analytics_token', token); try { const r=await fetch('/api/analytics-summary?days=30',{headers:{authorization:`Bearer ${token}`}}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'Could not load'); setData(j); } catch(e){setError((e as Error).message)} finally{setBusy(false)} };
  const max = Math.max(1, ...(data?.daily.map((d)=>d[1]) ?? [1]));
  return <div className="nice-scroll min-h-0 flex-1 overflow-y-auto bg-[#f5f0e7] p-5 text-ink sm:p-8"><main className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brass">Owner dashboard</p><h1 className="font-display mt-2 text-4xl">Journey + launch control</h1></div><a href="/" className="text-sm underline">Back to site</a></div>
    <div className="mt-7 flex max-w-xl gap-2"><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="ANALYTICS_DASHBOARD_TOKEN" className="min-w-0 flex-1 border border-ink/20 bg-white px-3 py-2 text-sm"/><button onClick={load} className="bg-ink px-5 py-2 text-sm font-bold text-white">{busy?'Loading…':'Load 30 days'}</button></div>{error&&<p className="mt-2 text-sm text-red-700">{error}</p>}
    {data ? <><div className="mt-8 grid gap-3 sm:grid-cols-3">{[['Visitors',data.visitors],['Sessions',data.sessions],['Events',data.events]].map(([k,v])=><div key={k} className="bg-white p-5 shadow-sm"><div className="text-xs uppercase tracking-widest text-ink-muted">{k}</div><div className="font-display mt-2 text-4xl">{v}</div></div>)}</div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="bg-white p-5"><h2 className="font-display text-2xl">Conversion funnel</h2><div className="mt-5 space-y-3">{data.funnel.map((f,i)=>{const prev=i?data.funnel[i-1].count:f.count;const pct=prev?Math.round(f.count/prev*100):0;return <div key={f.event}><div className="flex justify-between text-sm"><span>{label(f.event)}</span><span>{f.count}{i>0?` · ${pct}% from prior`:''}</span></div><div className="mt-1 h-3 bg-stone-100"><div className="h-full bg-[#8a6a3c]" style={{width:`${data.funnel[0].count?f.count/data.funnel[0].count*100:0}%`}}/></div></div>})}</div></section>
    <section className="bg-white p-5"><h2 className="font-display text-2xl">Activity by day</h2><div className="mt-5 flex h-48 items-end gap-1">{data.daily.map(([d,n])=><div key={d} title={`${d}: ${n}`} className="min-w-1 flex-1 bg-deepGreen" style={{height:`${Math.max(3,n/max*100)}%`}}/>)}</div></section></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-3">{[['Top products',data.products],['Sources',data.sources],['Devices',data.devices]].map(([title,rows])=><section key={title as string} className="bg-white p-5"><h2 className="font-display text-xl">{title as string}</h2><ol className="mt-4 space-y-2 text-sm">{(rows as [string,number][]).map(([k,n])=><li key={k} className="flex justify-between gap-2"><span>{k}</span><b>{n}</b></li>)}</ol></section>)}</div></> : <p className="mt-8 rounded border border-dashed border-ink/25 p-6 text-sm text-ink-muted">Enter the private Netlify dashboard token. The dashboard stores no customer names, emails, or message text.</p>}
    <section className="mt-8 bg-white p-5"><h2 className="font-display text-2xl">Product readiness</h2><p className="mt-1 text-sm text-ink-muted">Modeled values are a screening gate; every pilot SKU still needs a packed physical prototype.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b"><th className="py-2">Product</th><th>Status</th><th>Panels</th><th>Packed</th><th>Ship model</th><th>First action</th></tr></thead><tbody>{products.map(({p,bom,launch})=><tr key={p.id} className="border-b border-stone-100"><td className="py-3 font-bold">{p.name}</td><td>{launch.status}</td><td>{bom.panelCount}</td><td>{bom.fulfillment.packed.length}″ · {bom.fulfillment.packed.weightLb} lb</td><td>{bom.fulfillment.lane}{bom.fulfillment.shippingEstimate?` · $${bom.fulfillment.shippingEstimate}`:''}</td><td>{launch.requiredChecks[0]}</td></tr>)}</tbody></table></div></section>
  </main></div>;
}
